### PR TITLE
Expose a flush function which proxies to the seq-logger

### PR DESCRIPTION
**Pull request by raybooysen**

### CODE REVIEW

**Comment by raybooysen** [comment]
Hi @nblumhardt. I'm hoping you can accept this PR.  Our usecase is that we have a very short-running process in our app.  this process runs and dies before any events that have been queued are sent to seq. 

We'd like to expose the underlying logger's flush function so we can trigger and wait for this appropriately

**Comment by nblumhardt** [comment]
Thanks Ray, this seems like a gap that we should fill. `flush()` is fine, but (it's been a long time since I was particularly immersed in Node) just wondering whether this should be called `end()` to fit with Node stream API conventions? (Apologies if I'm miles off the mark, here :-))

**Comment by raybooysen** [comment]
Good point.  However we're not ending the stream.  You could feasibly call flush() at some important time and then let the stream continue working after.

I.e. calling flush doesn't stop the stream, it just jumps the queue for dequeuing the items.

**Comment by nblumhardt** [comment]
Great, thanks - will merge as is :-) 👍 ... Not sure if builds will be published automatically, but will check in on this early in the week.

**Comment by raybooysen** [comment]
Thanks!

**Comment by nblumhardt** [comment]
Was stalled a little by the GitHub outage yesterday; now onto figuring out why NPM publishing is failing - shoudn't be too far away.

**Comment by raybooysen** [comment]
Was this published?

**Comment by nblumhardt** [comment]
Hi Ray - yes, this should be out in 0.3. Let me know if it's not showing up for you.

**Comment by tjrobinson** [comment]
The `flush()` function doesn't seem to be available/accessible anymore - is it no longer needed, or replaced by something else?

**Comment by larenelg** [comment]
Hi @tjrobinson - `flush()` has been renamed to `flushBuffer()` and moved to `seq_string_transform.js` as per — https://github.com/datalust/bunyan-seq/pull/17/files

There's been a few changes around `flush` based on changing node patterns, I believe. Please forgive me that I don't have any more context than this right now, and let me know if that is enough information to unblock you? Otherwise, happy to look closer at it if it's causing issues.

**Comment by tjrobinson** [comment]
@larenelg Thanks, that helps a bit though I'm still struggling to work out how I'd call it. I'm using TypeScript which may be complicating the issue. I'm also referencing `"@types/bunyan-seq": "^0.2.2",` which is out of date I think.

What I have (simplified) is:

```typescript
import * as bunyan from "bunyan";
import * as seq from "bunyan-seq";

export class MyLogger {

  public bunyanLogger: bunyan;

  public seqStream: bunyan.Stream;

  constructor() {
    this.seqStream = seq.createStream({
      serverUrl: process.env["SEQ_URL"],
      apiKey: process.env["SEQ_API_KEY"],
      level: process.env["SEQ_LOG_LEVEL"] ?? "info"
    });

    const loggerOptions = <bunyan.LoggerOptions>{
      name: "My Application",
      streams: [
        this.seqStream
      ],
    }

    this.bunyanLogger = bunyan.createLogger(loggerOptions);
  }
}
```

I'm not sure where `seq_string_transform.js` would fit into this?

**Comment by larenelg** [comment]
Hi @tjrobinson sorry that I missed this followup! I'm going to move this discussion into an issue linking to your reply so that I can find it easily :) I'm doing an overall review of all the Seq Node.js libraries over the coming months, so your feedback is really appreciated! https://github.com/datalust/bunyan-seq/issues/27

**Pull request merged**
